In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
%matplotlib inline

In [2]:
data= pd.read_csv('home_price.csv')
data.head()

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [3]:
#Filling null value with median
import math
median_bedroom= math.floor(data.Bedroom.median())
median_bedroom

3

In [4]:
data.Bedroom= data.Bedroom.fillna(median_bedroom)
data

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [5]:
#Regression
reg= linear_model.LinearRegression()
reg.fit(data[['Area', 'Bedroom', 'Age']], data.Price)

LinearRegression()

In [6]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [7]:
reg.intercept_

383724.9999999998

In [8]:
#In order of Area, Bedroom, Age
reg.predict([[4000, 5, 8]])

array([748000.])

In [9]:
reg.predict([[5000, 5, 10]])

array([871600.])